### ISSUE TITLE
Gatsby page down?

### ISSUE THREAD

**Issue by santiagodiazl** [konstantinmuenster/gatsby-starter-portfolio-minimal#14]
Hi,

Not sure if you're aware but for some reason your Gatsby starter page is not being found: https://www.gatsbyjs.com/starters/konstantinmuenster/gatsby-starter-portfolio-minimal

Excellent work by the way.

**Comment by konstantinruge** [comment]
Hey! Thanks for mentioning it! Apparently, they changed their Starter library requirements. Since this repository here is deprecated, I won't update this starter project. But I will update it accordingly in the new Portfolio Minimal project: https://github.com/konstantinmuenster/gatsby-starter-portfolio-minimal-theme
